fixes related to a new version of rbfeeder:armhf and some general cleanup (#184)
* use native on all arm archs, cleanup logging

* fix - changelog.gz doesn't always exist

* add check for CPU serial number (again required from rbfeeder 1.0.9)

* doc update: ensure hexdump is installed when adding FakeCpuSerial

* only explicitly load armhf packages when arch needs to be emulated

* fix typo

* only do `dpkg --add-architecture armhf` when really needed

* remove i386 building from test builds

* make checking for cpu serial case independent

diff --git a/rootfs/etc/s6-overlay/scripts/02-rbfeeder b/rootfs/etc/s6-overlay/scripts/02-rbfeeder
--- a/rootfs/etc/s6-overlay/scripts/02-rbfeeder
+++ b/rootfs/etc/s6-overlay/scripts/02-rbfeeder
@@ -1,22 +1,25 @@
 #!/command/with-contenv bash
-# shellcheck shell=bash
+#shellcheck shell=bash disable=SC1091,SC2015
+
+source /scripts/common
+s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)
 
 # Check to make sure the correct command line arguments have been set
 EXITCODE=0
 if [ -z "${LAT}" ]; then
-  echo "ERROR: LAT environment variable not set"
+  "${s6wrap[@]}" echo "[ERROR] LAT environment variable not set"
   EXITCODE=1
 fi
 if [ -z "${LONG}" ]; then
-  echo "ERROR: LONG environment variable not set"
+  "${s6wrap[@]}" echo "[ERROR] LONG environment variable not set"
   EXITCODE=1
 fi
 if [ -z "${BEASTHOST}" ]; then
-  echo "ERROR: BEASTHOST environment variable not set"
+  "${s6wrap[@]}" echo "[ERROR] BEASTHOST environment variable not set"
   EXITCODE=1
 fi
 if [ -z "${ALT}" ]; then
-  echo "ERROR: ALT environment variable not set"
+  "${s6wrap[@]}" echo "[ERROR] ALT environment variable not set"
   EXITCODE=1
 else
   ALT="${ALT%%.*}"
@@ -27,9 +30,9 @@ fi
 
 # Set up timezone
 if [ -z "${TZ}" ]; then
-  echo "WARNING: TZ environment variable not set"
+  "${s6wrap[@]}" echo "[WARNING] TZ environment variable not set"
 else
-  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
+  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone || true
 fi
 
 # Generate /etc/rbfeeder.ini based on environment variables
@@ -42,11 +45,11 @@ debug_level=${DEBUG_LEVEL:-0}
 
 if [ -z "${SHARING_KEY}" ]
 then
-  echo ""
-  echo "WARNING: SHARING_KEY environment variable was not set!"
-  echo "Please make sure you note down the key generated."
-  echo "Pass the key as environment var SHARING_KEY on next launch!"
-  echo ""
+  "${s6wrap[@]}" echo ""
+  "${s6wrap[@]}" echo "[WARNING] SHARING_KEY environment variable was not set!"
+  "${s6wrap[@]}" echo "          Please make sure you note down the key generated."
+  "${s6wrap[@]}" echo "          Pass the key as environment var SHARING_KEY on next launch!"
+  "${s6wrap[@]}" echo ""
 else
   echo "key=$SHARING_KEY" >> /etc/rbfeeder.ini
 fi
@@ -90,8 +93,18 @@ if [[ -n "$UAT_RECEIVER_HOST" ]]; then
   } >> /etc/rbfeeder.ini
 fi
 
+if ! grep -qi "Serial\s*:" /proc/cpuinfo; then
+  # rbfeeder won't work without a serial number
+  "${s6wrap[@]}" echo ""
+  "${s6wrap[@]}" echo "[ERROR] Your machine doesn't have a serial number in /proc/cpuinfo"
+  "${s6wrap[@]}" echo "        You must resolve this for the container to run. Instruction to fix it can be found here:"
+  "${s6wrap[@]}" echo "        https://github.com/sdr-enthusiasts/docker-radarbox/blob/main/version_0.4.3_workarounds.md#workaround-for-cpu-serial"
+  sleep infinity & wait $!
+fi
+
 # Create log dirs
 mkdir -p /var/log/rbfeeder
+mkdir -p /run/shm
 chown nobody:nogroup /var/log/rbfeeder
 touch /var/log/rbfeeder.log
 truncate --size=0 /var/log/rbfeeder.log
