add check for CPU serial number (again required from rbfeeder 1.0.9)

diff --git a/rootfs/etc/s6-overlay/scripts/02-rbfeeder b/rootfs/etc/s6-overlay/scripts/02-rbfeeder
--- a/rootfs/etc/s6-overlay/scripts/02-rbfeeder
+++ b/rootfs/etc/s6-overlay/scripts/02-rbfeeder
@@ -1,5 +1,5 @@
 #!/command/with-contenv bash
-#shellcheck shell=bash disable=SC1091
+#shellcheck shell=bash disable=SC1091,SC2015
 
 source /scripts/common
 s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)
@@ -93,8 +93,18 @@ if [[ -n "$UAT_RECEIVER_HOST" ]]; then
   } >> /etc/rbfeeder.ini
 fi
 
+if ! grep -q "serial\s*:" /proc/cpuinfo; then
+  # rbfeeder won't work without a serial number
+  "${s6wrap[@]}" echo ""
+  "${s6wrap[@]}" echo "[ERROR] Your machine doesn't have a serial number in /proc/cpuinfo"
+  "${s6wrap[@]}" echo "        You must resolve this for the container to run. Instruction to fix it can be found here:"
+  "${s6wrap[@]}" echo "        https://github.com/sdr-enthusiasts/docker-radarbox/blob/main/version_0.4.3_workarounds.md#workaround-for-cpu-serial"
+  sleep infinity & wait $!
+fi
+
 # Create log dirs
 mkdir -p /var/log/rbfeeder
+mkdir -p /run/shm
 chown nobody:nogroup /var/log/rbfeeder
 touch /var/log/rbfeeder.log
 truncate --size=0 /var/log/rbfeeder.log
